(function(window){'use strict';var debug=false,counter=0,lastPopTime=0,baseName='SmartPopunder',parent=top!=self?top:self,userAgent=navigator.userAgent.toLowerCase(),browser={webkit:/webkit/.test(userAgent),mozilla:/mozilla/.test(userAgent)&&!/(compatible|webkit)/.test(userAgent),chrome:/chrome/.test(userAgent),msie:/msie|trident\//.test(userAgent)&&!/opera/.test(userAgent),firefox:/firefox/.test(userAgent),safari:/safari/.test(userAgent)&&!/chrome/.test(userAgent),opera:/opera/.test(userAgent),version:parseInt(userAgent.match(/(?:[^\s]+(?:ri|ox|me|ra)\/|trident\/.*?rv:)([\d]+)/i)[1],10)},helper={simulateClick:function(url){var a=this.createElement('a',{href:url||'data:text/html,<script>window.close();<\/script>;'}),evt=document.createEvent('MouseEvents');document.body.appendChild(a);evt.initMouseEvent('click',true,true,window,0,0,0,0,0,true,false,false,true,0,null);a.dispatchEvent(evt);a.parentNode.removeChild(a);},blur:function(popunder){try{popunder.blur();popunder.opener.window.focus();window.self.window.focus();window.focus();if(browser.firefox){this.openCloseWindow(popunder);}else if(browser.webkit){if(!browser.chrome||(browser.chrome&&browser.version<41)){this.openCloseTab();}}else if(browser.msie){setTimeout(function(){popunder.blur();popunder.opener.window.focus();window.self.window.focus();window.focus();},1000);}}catch(err){}},createElement:function(tag,attrs,text){var element=document.createElement(tag);for(var i in attrs){element.setAttribute(i,attrs[i]);}
if(text){element.innerHTML=innerHTML;}
return element;},openCloseWindow:function(popunder){var tmp=popunder.window.open('about:blank');tmp.focus();tmp.close();setTimeout(function(){try{tmp=popunder.window.open('about:blank');tmp.focus();tmp.close();}catch(e){}},1);},openCloseTab:function(){this.simulateClick();},isFlashInstalled:function(){return!!navigator.mimeTypes['application/x-shockwave-flash'];},removeFlashPopunder:function(pop){setTimeout(function(){var flash=document.getElementById(pop.name+'_flash');if(flash){flash.parentNode.removeChild(flash);}},1e3);},initFlashPopunder:function(pop){if(!this.isFlashInstalled)return;var self=this,identifier=pop.name+'_flash',timer,i,object=this.createElement('object',{'type':'application/x-shockwave-flash','data':Popunder.flashUrl,'name':identifier,'id':identifier,'style':'position:fixed;visibility:visible;left:0;top:0;width:1px;height:1px;z-index:9999999;'}),params=[{name:'flashvars',value:'fire='+ pop.name+'.fire&name='+ pop.name},{name:'wmode',value:'transparent'},{name:'menu',value:'false'},{name:'allowscriptaccess',value:'always'}];for(i in params){object.appendChild(this.createElement('param',params[i]));}
timer=setInterval(function(){if(document.readyState=='complete'){clearInterval(timer);document.body.insertBefore(object,document.body.firstChild);object.focus();self.attachEvent('mousedown',function(obj){if(obj.button===0){document.getElementById(identifier).style.width=document.getElementById(identifier).style.height='100%';}});}},10);return object;},detachEvent:function(event,callback,object){var object=object||window;if(!object.removeEventListener){return object.detachEvent('on'+ event,callback);}
return object.removeEventListener(event,callback);},attachEvent:function(event,callback,object){var object=object||window;if(!object.addEventListener){return object.attachEvent('on'+ event,callback);}
return object.addEventListener(event,callback);},mergeObject:function(){var obj={},i,k;for(i=0;i<arguments.length;i++){for(k in arguments[i]){obj[k]=arguments[i][k];}}
return obj;},getCookie:function(name){var cookieMatch=document.cookie.match(new RegExp(name+'=[^;]+','i'));return cookieMatch?decodeURIComponent(cookieMatch[0].split('=')[1]):null;},setCookie:function(name,value,expires,path){if(expires===null||typeof expires=='undefined'){expires='';}else{var date;if(typeof expires=='number'){date=new Date();date.setTime(date.getTime()+ expires*60*1e3);}else{date=expires;}
expires='; expires='+ date.toUTCString();}
document.cookie=name+'='+ escape(value)+ expires+'; path='+(path||'/');}},Popunder=function(url,options){this.__construct(url,options);};Popunder.flashUrl='flash/flash.swf';Popunder.prototype={defaultWindowOptions:{width:window.screen.width,height:window.screen.height,left:0,top:0,location:1,toolbar:1,status:1,menubar:1,scrollbars:1,resizable:1},defaultPopOptions:{cookieExpires:null,cookiePath:'/',newTab:true,blur:true,chromeDelay:500,beforeOpen:function(){},afterOpen:function(){}},__newWindowOptionsFlash:{menubar:0,toolbar:0},__newWindowOptionsChromeBefore41:{scrollbars:1},__construct:function(url,options){this.url=url;this.index=counter++;this.name=baseName+'_'+(this.index);this.executed=false;this.setOptions(options);this.register();window[this.name]=this;},register:function(){if(this.isExecuted())return;if(this.options.blur&&!this.options.newTab){helper.initFlashPopunder(this);}
var self=this,event='click',run=function(){if(self.shouldExecute()){self.fire();helper.detachEvent(event,run,window);helper.detachEvent(event,run,document);}};helper.attachEvent(event,run,window);helper.attachEvent(event,run,document);},fire:function(name){var self=window[name]||this,w;self.options.beforeOpen.call(undefined,this);lastPopTime=new Date().getTime();self.setExecuted();if(self.options.newTab){if(browser.chrome&&browser.version>30&&self.options.blur){window.open('javascript:window.focus()','_self','');helper.simulateClick(self.url);w=null;}else{w=parent.window.open(self.url,'_blank');}}else{w=window.open(self.url,self.url,self.getParams());}
self.options.afterOpen.call(undefined,this);if(self.options.blur){helper.blur(w);}
helper.removeFlashPopunder(self);},shouldExecute:function(){if(browser.chrome&&lastPopTime&&lastPopTime+ this.options.chromeDelay>new Date().getTime()){return false;}
return!this.isExecuted();},isExecuted:function(){if(debug){return this.executed;}
return this.executed||!!helper.getCookie(this.name);},setExecuted:function(){this.executed=true;helper.setCookie(this.name,1,this.options.cookieExpires,this.options.cookiePath);},setOptions:function(options){this.options=helper.mergeObject(this.defaultWindowOptions,this.defaultPopOptions,options||{});if(!this.options.newTab){if(browser.chrome&&browser.version<41){for(var k in this.__newWindowOptionsChromeBefore41){this.options[k]=this.__newWindowOptionsChromeBefore41[k];}}
if(helper.isFlashInstalled()){for(var k in this.__newWindowOptionsFlash){this.options[k]=this.__newWindowOptionsFlash[k];}}}},getParams:function(){var params='',k;for(k in this.options){if(typeof this.defaultWindowOptions[k]!='undefined'){params+=(params?',':'')+ k+'='+ this.options[k];}}
return params;}};Popunder.make=function(url,options){return new this(url,options);};window.SmartPopunder=Popunder;})(this);
