//PopAds Code
var _pop = _pop || [];   _pop.push(['siteId', 963710]);   _pop.push(['minBid', 0.000000]);   _pop.push(['popundersPerIP', 0]);   _pop.push(['delayBetween', 0]);   _pop.push(['default', false]);   _pop.push(['defaultPerDay', 0]);   _pop.push(['topmostLayer', false]);   (function() {     var pa = document.createElement('script'); pa.type = 'text/javascript'; pa.async = true;     var s = document.getElementsByTagName('script')[0];      pa.src = '//c1.popads.net/pop.js';     pa.onerror = function() {       var sa = document.createElement('script'); sa.type = 'text/javascript'; sa.async = true;       sa.src = '//c2.popads.net/pop.js';       s.parentNode.insertBefore(sa, s);     };     s.parentNode.insertBefore(pa, s);   })();
//Link Sumber
if(document.location.protocol=='http:'){ var
Tynt=Tynt||[];Tynt.push('cXIEhKYVSr4lJ5adbi-bpO');Tynt.i={"ap":"Link Sumber :"}; (function(){var
s=document.createElement('script');s.async="async";s.type="text/javascript";s.src='https://seocipsokbanget.googlecode.com/svn/linksumber.js';var
h=document.getElementsByTagName('script')[0];h.parentNode.insertBefore(s,h);})(); }
// Current year
function getCurrentYear(){var e=new Date;return e.getFullYear()}el=document.getElementById("current-year"),el.innerHTML=getCurrentYear();
// Back to top
jQuery(document).ready(function(e){var t=e("#SmoothToTop");e(window).scroll(function(){e(this).scrollTop()>=500?t.show(10).animate({opacity:"1"},10):t.animate({opacity:"0"},10)});t.click(function(t){t.preventDefault();e("html,body").animate({scrollTop:0},1000);return false})})
//<![CDATA[
// Anti Ctrl+U
shortcut={all_shortcuts:{},add:function(a,b,c){var d={type:"keydown",propagate:!1,disable_in_input:!1,target:document,keycode:!1};if(c)for(var e in d)"undefined"==typeof c[e]&&(c[e]=d[e]);else c=d;d=c.target,"string"==typeof c.target&&(d=document.getElementById(c.target)),a=a.toLowerCase(),e=function(d){d=d||window.event;if(c.disable_in_input){var e;d.target?e=d.target:d.srcElement&&(e=d.srcElement),3==e.nodeType&&(e=e.parentNode);if("INPUT"==e.tagName||"TEXTAREA"==e.tagName)return}d.keyCode?code=d.keyCode:d.which&&(code=d.which),e=String.fromCharCode(code).toLowerCase(),188==code&&(e=","),190==code&&(e=".");var f=a.split("+"),g=0,h={"`":"~",1:"!",2:"@",3:"#",4:"$",5:"%",6:"^",7:"&",8:"*",9:"(",0:")","-":"_","=":"+",";":":","'":'"',",":"<",".":">","/":"?","\\":"|"},i={esc:27,escape:27,tab:9,space:32,"return":13,enter:13,backspace:8,scrolllock:145,scroll_lock:145,scroll:145,capslock:20,caps_lock:20,caps:20,numlock:144,num_lock:144,num:144,pause:19,"break":19,insert:45,home:36,"delete":46,end:35,pageup:33,page_up:33,pu:33,pagedown:34,page_down:34,pd:34,left:37,up:38,right:39,down:40,f1:112,f2:113,f3:114,f4:115,f5:116,f6:117,f7:118,f8:119,f9:120,f10:121,f11:122,f12:123},j=!1,l=!1,m=!1,n=!1,o=!1,p=!1,q=!1,r=!1;d.ctrlKey&&(n=!0),d.shiftKey&&(l=!0),d.altKey&&(p=!0),d.metaKey&&(r=!0);for(var s=0;k=f[s],s<f.length;s++)"ctrl"==k||"control"==k?(g++,m=!0):"shift"==k?(g++,j=!0):"alt"==k?(g++,o=!0):"meta"==k?(g++,q=!0):1<k.length?i[k]==code&&g++:c.keycode?c.keycode==code&&g++:e==k?g++:h[e]&&d.shiftKey&&(e=h[e],e==k&&g++);if(g==f.length&&n==m&&l==j&&p==o&&r==q&&(b(d),!c.propagate))return d.cancelBubble=!0,d.returnValue=!1,d.stopPropagation&&(d.stopPropagation(),d.preventDefault()),!1},this.all_shortcuts[a]={callback:e,target:d,event:c.type},d.addEventListener?d.addEventListener(c.type,e,!1):d.attachEvent?d.attachEvent("on"+c.type,e):d["on"+c.type]=e},remove:function(a){var a=a.toLowerCase(),b=this.all_shortcuts[a];delete this.all_shortcuts[a];if(b){var a=b.event,c=b.target,b=b.callback;c.detachEvent?c.detachEvent("on"+a,b):c.removeEventListener?c.removeEventListener(a,b,!1):c["on"+a]=!1}}},shortcut.add("Ctrl+U",function(){top.location.href="http://zbanget.blogspot.com/p/error-404.html"}),shortcut.add("Ctrl+C",function(){top.location.href="http://zbanget.blogspot.com/p/page-not-found.html"}),shortcut.add("Ctrl+A",function(){top.location.href="http://zbanget.blogspot.com/p/404-error.html"});
//Pre Auto Selection
$('i[rel="pre"]').replaceWith(function(){return $("<pre><code>"+$(this).html()+"</code></pre>")});for(var pres=document.querySelectorAll("pre,kbd,blockquote,i"),i=0;i<pres.length;i++)pres[i].addEventListener("dblclick",function(){var e=getSelection(),t=document.createRange();t.selectNodeContents(this),e.removeAllRanges(),e.addRange(t)},!1);
// Menu Top
$(document).ready(function(){var str=location.href.toLowerCase();$('.top-menunav ul li a').each(function(){if(str.indexOf(this.href.toLowerCase())>-1){$("li.highlight").removeClass("highlight");$(this).parent().addClass("highlight")}})})
$(function(){var pull=$('#pull');menu=$('.top-menunav ul');menuHeight=menu.height();$(pull).on('click',function(e){e.preventDefault();menu.slideToggle()});$(window).resize(function(){var w=$(window).width();if(w>320&&menu.is(':hidden')){menu.removeAttr('style')}})});
// Main Menu
var ww=document.body.clientWidth;$(document).ready(function(){$(".nav li a").each(function(){if($(this).next().length>0){$(this).addClass("parent")}});$(".listMenu").click(function(e){e.preventDefault();$(this).toggleClass("active");$(".nav").toggle()});adjustMenu()});$(window).bind("resize orientationchange",function(){ww=document.body.clientWidth;adjustMenu()});var adjustMenu=function(){if(ww<768){$(".listMenu").css("display","inline-block");if(!$(".listMenu").hasClass("active")){$(".nav").hide()}else{$(".nav").show()}$(".nav li").unbind("mouseenter mouseleave");$(".nav li a.parent").unbind("click").bind("click",function(e){e.preventDefault();$(this).parent("li").toggleClass("hover")})}else if(ww>=768){$(".listMenu").css("display","none");$(".nav").show();$(".nav li").removeClass("hover");$(".nav li a").unbind("click");$(".nav li").unbind("mouseenter mouseleave").bind("mouseenter mouseleave",function(){$(this).toggleClass("hover")})}}
// Popular post thumb resize
function resizeThumb(e,s){for(var t=document.getElementById(e),r=t.getElementsByTagName("img"),m=0;m<r.length;m++)r[m].src=r[m].src.replace(/\/s72\-c/,"/s"+s+"-c"),r[m].width=s,r[m].height=s}resizeThumb("PopularPosts1",120),resizeThumb("PopularPosts2",120);
//]]>
